---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-secret
  namespace: default
spec:
  encryptedData:
    PASSWORD: AgA4Mm6xapppfxTBkpsVLNSqlAb380eUrDwMwMJFJpPniJIh9KWTZd7rJ7BEB0ZaXpfvQFCF8jr5Mm5baLf+gDPLB1bGe5fzmmVaqD/lJXavKMgjq64qyj7TrHrkPc2sYnFtL5iYMol6e2eGDnVq+x/CSePFN4d4YYhEgBTgPAEpl3yfaN6B5evP6hXkWvm8gzW5Fi7xYrYUXSNIuhtB/j+Kj3OuVAeOQGrIObZ/3TQppUkjbxOQRd8kV0XCHj4L7VLc/hOsERefavdWjfEsGDIizBnY6k+RlaseoDIOZ5O2jEWJEAkkyW1p4jAYaJEtzNBkYpDrmrbvtjX2xcPhFGx96BrRXp061dIZ0SExC38GqIvDE6zFMt+Vk717JK/wTpNZQqeiialEEtAJGq29bY5JkrMWhNBUShzxvafU/HJw/9gUUUJadiwOg0L4a44p7tgrN3V+eVlSrDuaMLDc5Bd7IRL1Y8G01RizBSfQL56Ig/z9ZX7pdNef5U38WY2zoaagh9OlGDKTsH5zeu6tEAt40Mu672NhiGhycBKjhQHDIQBeXX7xOT2hH0BaywTvWq/2WEsRV0h+pzlH+h4t0YDuwqQUqILQ1puTDJ3q1KUKMV+ynM0Iy8mLyz0Jd1GXnWcsTgShdySV4a6uuC/diZ+3dZniURL55JV5CcexDN61AbUOEzrllI5KA+ZovZHWoU2pVNpFIX3v
  template:
    metadata:
      creationTimestamp: null
      name: test-secret
      namespace: default
